spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: test
    url: jdbc:postgresql://127.0.0.1:5432/spring_cloud_dev

server:
  port: 8081

# Eurekaの情報
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/